### ISSUE TITLE
Initial download error

### ISSUE THREAD

**Issue by arboeh** [nolageek/Discogs-Collection-Page#5]
HI there! I get the following error on initial download of the collection:

> Task: Updating ALL
Task: Updating Collection
Downloading Collection List To collection.json
Pausing for 1 seconds   due to API limits.
Task: Updating IMAGES
1/320:
1/320:  Downloading Odyssey (The Definitive Collection) (./img/239673.jpeg)
Downloading image for Odyssey (The Definitive Collection)
Traceback (most recent call last):
  File "./update-discogs.py", line 152, in <module>
    main()
  File "./update-discogs.py", line 72, in main
    update_images()
  File "./update-discogs.py", line 137, in update_images
    download_image(
  File "./update-discogs.py", line 113, in download_image
    urllib.request.urlretrieve(url, IMG_DIR + str(id) + ".jpeg")
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by arboeh** [comment]
Fixed it myself. I will create an pull request.
